// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductosService.Data;

#nullable disable

namespace ProductosService.Migrations
{
    [DbContext(typeof(ProductosContext))]
    [Migration("20260405224826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductosService.Models.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductoID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoID = 1,
                            Activo = true,
                            Descripcion = "Laptop HP 15.6 pulgadas, 8GB RAM, 256GB SSD",
                            FechaCreacion = new DateTime(2026, 4, 5, 17, 48, 25, 185, DateTimeKind.Local).AddTicks(3772),
                            Nombre = "Laptop HP",
                            Precio = 850.99m,
                            Stock = 10
                        },
                        new
                        {
                            ProductoID = 2,
                            Activo = true,
                            Descripcion = "Mouse ergonómico inalámbrico",
                            FechaCreacion = new DateTime(2026, 4, 5, 17, 48, 25, 188, DateTimeKind.Local).AddTicks(8250),
                            Nombre = "Mouse Inalámbrico",
                            Precio = 25.50m,
                            Stock = 50
                        },
                        new
                        {
                            ProductoID = 3,
                            Activo = true,
                            Descripcion = "Teclado mecánico RGB",
                            FechaCreacion = new DateTime(2026, 4, 5, 17, 48, 25, 188, DateTimeKind.Local).AddTicks(8314),
                            Nombre = "Teclado Mecánico",
                            Precio = 75.00m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
